services:
  postgres-database:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: tranched
      POSTGRES_PASSWORD: password
      PGPORT: 5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"